grid_map_topic: /ga_slam_visualization/raw_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: meanZ
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: meanZ
     # data_min: 0.08
     data_min: -5.0
     # data_max: -0.16
     data_max: 5.0
